OrdererOrgs:
  - Name: Orderer
    Domain: hackerthon.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4

PeerOrgs:
  - Name: manufacturer
    Domain: manufacturer.hackerthon.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: distributor
    Domain: distributor.hackerthon.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: retailer
    Domain: retailer.hackerthon.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
