# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'hyperledger_fabric_metrics'
    scrape_interval: 10s
    static_configs:
    - targets: ['peer0.cpa.certverification.com:9443','peer1.cpa.certverification.com:9443','peer0.verifier.certverification.com:9443','peer1.verifier.certverification.com:9443','orderer0.certverification.com:9443','orderer1.certverification.com:9443','orderer2.certverification.com:9443','orderer3.certverification.com:9443','orderer4.certverification.com:9443']
  - job_name: 'docker_containers'
    scrape_interval: 10s
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'machine_metrics'
    scrape_interval: 10s
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'alert_manager'
    scrape_interval: 10s
    static_configs:
    - targets: ['alertmanager:9093']
