version: '2'

services:

  orderer0.hackerthon.com:
    container_name: orderer0.hackerthon.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.hackerthon.com:9443
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer0.hackerthon.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer0.hackerthon.com/tls/:/var/hyperledger/orderer/tls
        - orderer0.hackerthon.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer1.hackerthon.com:
    container_name: orderer1.hackerthon.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.hackerthon.com:9443
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer1.hackerthon.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer1.hackerthon.com/tls/:/var/hyperledger/orderer/tls
        - orderer1.hackerthon.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  orderer2.hackerthon.com:
    container_name: orderer2.hackerthon.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.hackerthon.com:9443
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer2.hackerthon.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer2.hackerthon.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.hackerthon.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  orderer3.hackerthon.com:
    container_name: orderer3.hackerthon.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer3.hackerthon.com:9443
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer3.hackerthon.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer3.hackerthon.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.hackerthon.com:/var/hyperledger/production/orderer
    ports:
      - 10050:7050

  orderer4.hackerthon.com:
    container_name: orderer4.hackerthon.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer4.hackerthon.com:9443
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer4.hackerthon.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/hackerthon.com/orderers/orderer4.hackerthon.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.hackerthon.com:/var/hyperledger/production/orderer
    ports:
      - 11050:7050


  peer0.manufacturer.hackerthon.com:
    container_name: peer0.manufacturer.hackerthon.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.manufacturer.hackerthon.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.hackerthon.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manufacturer.hackerthon.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.manufacturer.hackerthon.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.hackerthon.com:7051
      - CORE_OPERATIONS_LISTENADDRESS=peer0.manufacturer.hackerthon.com:9443
      - CORE_PEER_LOCALMSPID=manufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/manufacturer.hackerthon.com/peers/peer0.manufacturer.hackerthon.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/manufacturer.hackerthon.com/peers/peer0.manufacturer.hackerthon.com/tls:/etc/hyperledger/fabric/tls
        - peer0.manufacturer.hackerthon.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:6060

  peer1.manufacturer.hackerthon.com:
    container_name: peer1.manufacturer.hackerthon.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.manufacturer.hackerthon.com
      - CORE_PEER_ADDRESS=peer1.manufacturer.hackerthon.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.manufacturer.hackerthon.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manufacturer.hackerthon.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manufacturer.hackerthon.com:7051
      - CORE_OPERATIONS_LISTENADDRESS=peer1.manufacturer.hackerthon.com:9443
      - CORE_PEER_LOCALMSPID=manufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/manufacturer.hackerthon.com/peers/peer1.manufacturer.hackerthon.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/manufacturer.hackerthon.com/peers/peer1.manufacturer.hackerthon.com/tls:/etc/hyperledger/fabric/tls
        - peer1.manufacturer.hackerthon.com:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8052:6060


  peer0.distributor.hackerthon.com:
    container_name: peer0.distributor.hackerthon.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.distributor.hackerthon.com
      - CORE_PEER_ADDRESS=peer0.distributor.hackerthon.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.distributor.hackerthon.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.distributor.hackerthon.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.hackerthon.com:9051
      - CORE_OPERATIONS_LISTENADDRESS=peer0.distributor.hackerthon.com:9443
      - CORE_PEER_LOCALMSPID=distributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/distributor.hackerthon.com/peers/peer0.distributor.hackerthon.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/distributor.hackerthon.com/peers/peer0.distributor.hackerthon.com/tls:/etc/hyperledger/fabric/tls
        - peer0.distributor.hackerthon.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9052:6060

  peer1.distributor.hackerthon.com:
    container_name: peer1.distributor.hackerthon.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.distributor.hackerthon.com
      - CORE_PEER_ADDRESS=peer1.distributor.hackerthon.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.distributor.hackerthon.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.distributor.hackerthon.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.hackerthon.com:9051
      - CORE_OPERATIONS_LISTENADDRESS=peer1.distributor.hackerthon.com:9443
      - CORE_PEER_LOCALMSPID=distributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/distributor.hackerthon.com/peers/peer1.distributor.hackerthon.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/distributor.hackerthon.com/peers/peer1.distributor.hackerthon.com/tls:/etc/hyperledger/fabric/tls
        - peer1.distributor.hackerthon.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10052:6060


  peer0.retailer.hackerthon.com:
    container_name: peer0.retailer.hackerthon.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.retailer.hackerthon.com
      - CORE_PEER_ADDRESS=peer0.retailer.hackerthon.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer.hackerthon.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.hackerthon.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.retailer.hackerthon.com:12051
      - CORE_OPERATIONS_LISTENADDRESS=peer0.retailer.hackerthon.com:9443
      - CORE_PEER_LOCALMSPID=retailerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/retailer.hackerthon.com/peers/peer0.retailer.hackerthon.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/retailer.hackerthon.com/peers/peer0.retailer.hackerthon.com/tls:/etc/hyperledger/fabric/tls
        - peer0.retailer.hackerthon.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11052:6060

  peer1.retailer.hackerthon.com:
    container_name: peer1.retailer.hackerthon.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.retailer.hackerthon.com
      - CORE_PEER_ADDRESS=peer1.retailer.hackerthon.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.retailer.hackerthon.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.retailer.hackerthon.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.hackerthon.com:11051
      - CORE_OPERATIONS_LISTENADDRESS=peer1.retailer.hackerthon.com:9443
      - CORE_PEER_LOCALMSPID=retailerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/retailer.hackerthon.com/peers/peer1.retailer.hackerthon.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/retailer.hackerthon.com/peers/peer1.retailer.hackerthon.com/tls:/etc/hyperledger/fabric/tls
        - peer1.retailer.hackerthon.com:/var/hyperledger/production
    ports:
      - 12051:12051
      - 12052:6060